#!/bin/bash

set -e

cd "$(dirname "$0")/.."

rm -fr data/output/cypher data/output/direct_rdf data/output/interchange data/output/skos
rm -fr data/oxigraph/urn*
rm -fr history logs schedules storage
